pipeline {
    agent any

    environment {
        PYTHON = '/usr/bin/python3'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', 
                    credentialsId: 'github-cred',
                    url: 'https://github.com/yetmgetaredahegn/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    cd messaging_app
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    cd messaging_app
                    . venv/bin/activate
                    pytest --junitxml=test-results.xml
                '''
            }
        }

        stage('Report') {
            steps {
                junit 'messaging_app/test-results.xml'
            }
        }
    }
}
