services:
  db:
    image: mysql:8
    container_name: messaging_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "deAlto#Crack357"
      MYSQL_DATABASE: messaging_app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: "deAlto#Crack357"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: .
    container_name: messaging_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ./entrypoint.sh
    volumes:
      - .:/app

volumes:
  db_data: