pipeline {
    agent any  // Run this pipeline on any available Jenkins agent

    environment {
        VENV_DIR = 'venv' // Virtual environment folder
    }

    stages {

        stage('Clone Repo') {
            steps {
                // Clone your repository
                git branch: 'main', url: 'https://github.com/yetmgetaredahegn/alx-backend-python.git'
            }
        }

        stage('Setup Python Environment') {
            steps {
                // Create virtual environment
                sh 'python3 -m venv $VENV_DIR'
                // Activate and install dependencies
                sh '. $VENV_DIR/bin/activate && pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                // Activate venv and run pytest
                sh '. $VENV_DIR/bin/activate && pytest messaging_app/tests --junitxml=report.xml'
            }
        }

        stage('Archive Test Report') {
            steps {
                // Collect test report in Jenkins
                junit 'report.xml'
            }
        }
    }
}
