pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-cred',
                    url: 'https://github.com/yetmgetaredahegn/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                withPythonEnv('Python3') {
                    sh 'pip install -r messaging_app/requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                withPythonEnv('Python3') {
                    sh 'pytest messaging_app/tests/ --junitxml=report.xml'
                }
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }
}
